spring:
  application:
    name: BankRest

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_rest}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:nurs123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: ${SERVER_PORT:8080}
